---
gating_overrides_file: "/etc/openstack_deploy/user_zzz_gating_variables.yml"

default_gating_overrides:
  maas_notification_plan: npTechnicalContactsEmail
  nova_virt_type: qemu
  maas_auth_method: "token"
  maas_auth_token: "{{lookup('env', 'MAAS_AUTH_TOKEN')}}"
  maas_api_url: "{{lookup('env', 'MAAS_API_URL')}}"
  tempest_swift_container_sync: False
  tempest_swift_discoverable_apis:
    - bulk
    - object
    - container_quotas
    - slo
    - tempurl
  # NOTE(mattt): This can be removed once we drop gating osa's stable/mitaka
  tempest_tempest_conf_overrides:
    object-storage:
      reseller_admin_role: ResellerAdmin
    compute-feature-enabled:
      personality: false
      attach_encrypted_volume: false
    volume-feature-enabled:
      snapshot: true
  # This is being increased from the default of 85 as the default value may be
  # too low for the liberty->mitaka upgrade job where more space is used by
  # additional packages, venvs, logs, etc.
  percent_used_critical_threshold: 95
  # (alextricity25) Adding the cirros_*_url vars. This var has been dropped
  # from OSA in newton so we are carrying it here so we have support for both
  # newton and earlier releases.
  cirros_tgz_url: "http://download.cirros-cloud.net/{{ '{{' }} cirros_version {{ '}}' }}/cirros-{{ '{{' }}cirros_version{{ '}}' }}-x86_64-uec.tar.gz"
  cirros_img_url: "http://rpc-repo.rackspace.com/rpcgating/cirros-0.3.4-x86_64-dropbearmod.img"

  # (alextricity25) This variable is used to populate the image directives in
  # tempest.conf in stable/newton.
  # We can't rely on the upstream value of this variable to be the same as
  # cirros_img_url, so we also override this variable here.
  tempest_image_file: "cirros-0.3.4-x86_64-dropbearmod.img"
  tempest_images:
    - url: "{{ '{{' }}cirros_img_url{{ '}}' }}"
      sha256: "ec1120a9310ac3987feee4e3c5108d5d0fd0e594c4283804c17d673ebb2d3769"
    - url: "{{ '{{' }}cirros_tgz_url{{ '}}' }}"
      sha256: "95e77c7deaf0f515f959ffe329918d5dd23e417503d1d45e926a888853c90710"
