---
  - name: Get facts about servers with a given name
    local_action:
        module: rax_facts
        name: "{{ name }}"

  - name: Show IP of server with given name, fail if no such server exists in region
    debug: var=rax_accessipv4
    failed_when: rax_accessipv4 is undefined

  - name: Set ansible host to IP address of server with given name
    set_fact:
        ansible_host: "{{ rax_accessipv4 }}"

  - name: Add servers to cloud_instances host group
    local_action:
      module: add_host
      hostname: "{{ name }}"
      ansible_host: "{{ rax_accessipv4 }}"
      ansible_user: root
      groupname: cloud_instances

  - name: Wait for SSH to be available on host
    wait_for: port=22 host="{{ ansible_host }}"
